# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-case-conflict
          #- id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: check-merge-conflict
          - id: check-vcs-permalinks
          - id: check-yaml
            args: [--allow-multiple-documents]
          - id: destroyed-symlinks
          - id: detect-aws-credentials
            args: [--allow-missing-credentials]
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: no-commit-to-branch
    - repo: https://github.com/doublify/pre-commit-clang-format
      # Requires to be run under `bash`.
      # Requires installation of additional tool. Tool is available on Windows.
      # clang-format: sudo apt install clang-format
      # Some `.m` files are matlab specific and are incorrectly changed.
      # Configuration file: .clang-format
      rev: 62302476d0da01515660132d76902359bed0f782
      hooks:
          - id: clang-format
            args: [-style=file]
            files: (?i)\.(c|cpp|cc|cxx|c\+\+|m|mm|h|hpp|hh|hxx|h\+\+)$
            types: [file]
    - repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
      rev: v0.6.9
      hooks:
          - id: cmake-format
